
-- Heimdall color scheme overrides for Catppuccin
-- Generated by heimdall-cli

local M = {}

-- Define colors table
local colors = {
    -- Base colors 
		base = "#1E1E2E",
    mantle = "#181825",
    crust = "#11111B",
    
    -- Surface colors
    surface0 = "#313244",
    surface1 = "#45475A",
    surface2 = "#585B70",
    
    -- Overlay colors
    overlay0 = "#6C7086",
    overlay1 = "#7F849C",
    overlay2 = "#9399B2",
    
    -- Text colors
    text = "#CDD6F4",
    subtext0 = "#A6ADC8",
    subtext1 = "#BAC2DE",
    
    -- Catppuccin palette colors
    rosewater = "#F5E0DC",
    flamingo = "#F2CDCD",
    pink = "#F5C2E7",
    mauve = "#CBA6F7",
    red = "#F38BA8",
    maroon = "#EBA0AC",
    peach = "#FAB387",
    yellow = "#F9E2AF",
    green = "#A6E3A1",
    teal = "#94E2D5",
    sky = "#89DCEB",
    sapphire = "#74C7EC",
    blue = "#89B4FA",
    lavender = "#B4BEFE",
}

M.color_overrides = {
  all = colors,
}
M.colors = colors

return M
